name = "rally-start"
main = "src/index.js"
compatibility_date = "2024-09-01"

# Durable Object pour distribuer l'indice de départ
[durable_objects]
bindings = [
  { name = "START_COUNTER", class_name = "StartCounter" }
]

# Première migration pour enregistrer la classe DO
[[migrations]]
tag = "v1"
new_classes = ["StartCounter"]

[vars]
# Mets ici l'origine de ton site si tu veux restreindre le CORS
ALLOWED_ORIGIN = "*"
TOTAL_STATIONS = 20
